# 📘 Logistic Regression

## 🔍 What is Logistic Regression?

**Logistic Regression** is a supervised machine learning algorithm used for **classification** tasks. It predicts the **probability** of an input belonging to a certain class (typically binary: 0 or 1).

---

## ⚙️ How Does It Work?

1. Takes input features (e.g., age, income).
2. Applies a **linear equation**:  
   
   $z = w_0 + w_1x_1 + w_2x_2 + \dots + w_nx_n$
   
3. Passes `z` through a **sigmoid (logistic) function**:
   
   $h(x) = \frac{1}{1 + e^{-z}}$
4. Uses a **threshold** (usually 0.5):
   - If output ≥ 0.5 → Class 1
   - If output < 0.5 → Class 0

---

## ✅ Use Cases

- Email Spam Detection
- Medical Diagnosis (e.g., tumor prediction)
- Customer Churn Prediction
- Credit Card Fraud Detection

---

## 🔑 Advantages

- Simple and easy to implement
- Works well for binary classification
- Outputs probabilities (confidence)

---

## ⚠️ Limitations

- Assumes linear relationship between features and log-odds
- Not ideal for complex nonlinear relationships without transformations

---

# ❓ Why Not Use Linear Regression for Classification?

### 🚫 Problems with Linear Regression:

1. **Unbounded Outputs**  
   - Linear regression can output values like -1.3 or 2.5 ❌  
   - Classification requires probabilities between 0 and 1 ✅

2. **No Probabilistic Interpretation**  
   - Logistic regression gives meaningful probabilities (e.g., 85% chance of spam)
   - Linear regression does not

3. **Sensitive to Outliers**  
   - Can lead to incorrect boundaries for class labels

4. **Inaccurate Decision Boundary**  
   - Logistic regression provides a **sigmoid curve**, giving a **smooth** and **bounded** transition between classes

---

### 🟢 Example

| Age | Bought Product? (0 = No, 1 = Yes) |
|-----|----------------|
| 22  | 0              |
| 25  | 0              |
| 30  | 1              |
| 35  | 1              |

- **Linear Regression Prediction:**
  - Age 24 → 0.3  
  - Age 38 → 1.6 ❌ (invalid probability)

- **Logistic Regression Prediction:**
  - Age 24 → 0.25 ✅  
  - Age 38 → 0.95 ✅

---

## 🧠 Conclusion

> **Linear regression is not suitable for classification** because:
> - It does **not restrict outputs to 0–1**
> - It lacks **probabilistic meaning**
> - It produces **poor decision boundaries**
>  
> **Logistic regression** solves these issues using the **sigmoid function**.

---


# 📉 Logistic Regression Cost Function

## ❓ Why Do We Need a Cost Function?

In logistic regression, we predict **probabilities**, and we need a cost function that:
- Penalizes wrong predictions,
- Works well with the **sigmoid** output (non-linear),
- And helps the model learn by minimizing the error.

---

## 🚫 Why Not Use Mean Squared Error (MSE)?

MSE is used in linear regression, but it's not suitable here because:
- It results in a **non-convex cost function** for logistic regression.
- That makes it **hard for gradient descent** to converge.

---

## ✅ Logistic Loss / Binary Cross-Entropy

The cost function used in logistic regression is:

\[
J(\theta) = -\frac{1}{m} \sum_{i=1}^{m} \left[ y^{(i)} \log(h_\theta(x^{(i)})) + (1 - y^{(i)}) \log(1 - h_\theta(x^{(i)})) \right]
\]

Where:
- \( m \): number of training examples  
- \( h_\theta(x) \): predicted probability (sigmoid output)  
- \( y \): actual label (0 or 1)

---

## 🧠 Intuition

- If $( y = 1 )$, the cost is:  
  
  $-\log(h_\theta(x))$

  → penalizes small probabilities near 0

- If $( y = 0 )$, the cost is:  
  
  $-\log(1 - h_\theta(x))$
  
  → penalizes large probabilities near 1

---
Below is the graph showing the cost function behavior for `y = 1` and `y = 0`.

![Cost Function Graph](image.png)

In [3]:
from sklearn.datasets import load_iris

In [5]:
dataset=load_iris()
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
import pandas as pd
import numpy as np
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df['target']=dataset.target
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [10]:
## Binary Classification
df_copy=df[df['target']!=2]

In [11]:
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20, random_state=42)

In [15]:
classifier=LogisticRegression()

In [16]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [17]:
classifier.predict_proba(X_test)

array([[0.00118085, 0.99881915],
       [0.01580857, 0.98419143],
       [0.00303433, 0.99696567],
       [0.96964813, 0.03035187],
       [0.94251523, 0.05748477],
       [0.97160984, 0.02839016],
       [0.99355615, 0.00644385],
       [0.03169836, 0.96830164],
       [0.97459743, 0.02540257],
       [0.97892756, 0.02107244],
       [0.95512297, 0.04487703],
       [0.9607199 , 0.0392801 ],
       [0.00429472, 0.99570528],
       [0.9858324 , 0.0141676 ],
       [0.00924893, 0.99075107],
       [0.98144334, 0.01855666],
       [0.00208036, 0.99791964],
       [0.00125422, 0.99874578],
       [0.97463766, 0.02536234],
       [0.96123726, 0.03876274]])

In [19]:
## Prediction
y_pred=classifier.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [20]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int32

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [25]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Hyperparameter Tuning

In [26]:
## Gridsearchcv
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [27]:
parameters={'penalty':('l1','l2','elasticnet',None),'C':[1,10,20]}

In [28]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [29]:
## Splitting of Train data to validation data
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [30]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [31]:
classifier=LogisticRegression(C=1,penalty='l2')

In [32]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [33]:
## Prediction
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [34]:
## Reandomized Searchcv
from sklearn.model_selection import RandomizedSearchCV

In [35]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)

In [36]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [37]:
random_clf.best_params_

{'penalty': 'l2', 'C': 10}

## Logistic Regression For Multiclass Classification

In [38]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [39]:
# define the multinomial logistic regression model For multiclass classification
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [40]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [41]:
# trianing model
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [42]:
y_pred=model.predict(X_test)

In [43]:
model.predict_proba(X_test)

array([[9.10622335e-02, 5.88916888e-01, 3.20020878e-01],
       [7.74864218e-02, 8.83936419e-01, 3.85771592e-02],
       [6.84414416e-01, 2.03496841e-01, 1.12088744e-01],
       [1.43095699e-02, 9.01488946e-02, 8.95541536e-01],
       [6.87497205e-02, 8.36642893e-01, 9.46073865e-02],
       [1.09007702e-01, 3.07621844e-01, 5.83370453e-01],
       [3.78594000e-01, 2.08265604e-01, 4.13140396e-01],
       [3.14084906e-01, 1.75940674e-01, 5.09974420e-01],
       [5.14671931e-01, 1.90311178e-01, 2.95016891e-01],
       [5.97817613e-01, 3.02410459e-01, 9.97719283e-02],
       [4.20115939e-02, 3.31570100e-01, 6.26418306e-01],
       [4.86740270e-01, 1.04804858e-01, 4.08454873e-01],
       [8.01115911e-01, 3.37497449e-02, 1.65134344e-01],
       [8.98140961e-02, 6.97976196e-01, 2.12209707e-01],
       [7.29023255e-02, 8.39105805e-01, 8.79918698e-02],
       [5.10619176e-01, 2.09225440e-01, 2.80155384e-01],
       [1.24309039e-01, 7.90819633e-01, 8.48713286e-02],
       [3.42847759e-03, 3.71703

In [44]:
y_pred

array([1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,
       2, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 0, 1,
       2, 1, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1,
       0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0,
       2, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0,
       2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0])

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[56 10 17]
 [16 41  6]
 [ 3 13 38]]
0.675
              precision    recall  f1-score   support

           0       0.75      0.67      0.71        83
           1       0.64      0.65      0.65        63
           2       0.62      0.70      0.66        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200

